
### ===================================================== ###
#default
serverPort: 8080
debugLevel: DEBUG

#mysql
db-host: ec2-3-39-205-107.ap-northeast-2.compute.amazonaws.com
db-port: 3306
db-database: jungang
#redis
redis-host: 3.39.205.107
redis-port: 6379
redis-database: 0
#jpa
ddlAuto: update

---

#common
server:
  servlet:
    context-path: /api
  port: ${serverPort}

# i18n
spring:
  profiles: prod
  # output
  output:
    ansi:
      enabled: ALWAYS
  # jpa hibernate
  jpa:
    properties:
      hibernate:
        show-sql: false
        physical_naming_strategy: hoon.pepper.common.config.jpa.JpaPhysicalNamingStrategy
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: ${ddlAuto}
        id:
          new_generator_mappings: false
      hbm2ddl:
        auto: ${ddlAuto}
  # redis
  redis: # TODO
    database: ${redis-database}
    host: ${redis-host}
    port: ${redis-port}
    password: jungang123!@#
  # token
  token:
    prefix: Bearer
    key: pepper
    jwt:
      expire: 3600000       # 1 시간 - 1000 * 60 * 60
      header: Authorization
    refresh:
      expire: 86400000      # 1 일 - 1000 * 60 * 60 * 24
      header: RefreshToken


#  # task thread
#  task:
#    execution:
#      pool:
#        max-size: 30
#        queue-capacity: 10
#      thread-name-prefix: THREAD-
#  # rabbitmq
#  rabbitmq:
#    host: new-makers-rabbitmq-sandbox.pg1.krane.9rum.cc
#    port: 5672
#    username: ${vault.rabbitmq.username}
#    password: ${vault.rabbitmq.password}
#    listener:
#      simple:
#        prefetch: 20
#        default-requeue-rejected: false

# log
debug: true
logging:
  level:
    root: info
    org.springframework.boot.autoconfigure.logging: INFO
    org.springframework.web.client: ${debugLevel}
    org.hibernate: ${debugLevel}
    org.springframework.security: DEBUG
    hoon.pepper: trace
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p - [%t] %logger{39}.%M : %m%n"
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(-){faint} [%t] %clr(%logger{15}.%-30.30M){cyan} %clr(:){faint} %m%n%wEx"




# mysql database
datasource: # TODO
  host: ${db-host}
  port: ${db-port}
  database: ${db-database}
  username: jungang
  password: jungang123!@#
  hikari:
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-lifetime: 28797000
    minimum-idle: 6
    maximum-pool-size: 20

## Redisson
redisson: # TODO
  host: ${redis-host}
  port: ${redis-port}
  database: ${redis-database}
  password: jungang123!@#
  config:
    idleConnectionTimeout: 5000
    connectionPoolSize: 10
    connectionMinimumIdleSize: 5
    dnsMonitoringInterval: 5000
    timeout: 600000
